name: hb-gem-reconstruction
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cobra>=0.29
  - swiglpk>=5
  - pandas>=2
  - numpy>=1.26
  - scipy>=1.11
  - pyyaml>=6
  - lxml>=5
  - openpyxl>=3.1
  - nbformat>=5.9
  - nbclient>=0.9
  - jupyter
  - pip
  - pip:
      - memote==0.17.0
